### ISSUE TITLE
Clang build OpenMP requirement

### ISSUE THREAD

**Issue by solomonik** [springer13/hptt#5]
It would be nice to be able to build without OpenMP, for instance when using clang.  My understanding is external modules are still necessary to do clang + OpenMP.  My version of clang is

clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix

I get the following error when building with `-fopenmp` or without

````
src/hptt.cpp:29:10: fatal error: 'omp.h' file not found
#include <omp.h>
````

**Comment by LaurentPlagne** [comment]
I agree. 
In addition, I am not totally confident about the zero overhead of a single threaded (numThreads=1) OMP version compared to a non OMP one. 
Several sequential transpositions could run in concurrent threads...

**Comment by springer13** [comment]
I have just pushed a version which doesn't rely on openmp anylonger. However, I was still having problem to build with clang 3.8 (and 3.9). A quick workaround would be to build the scalar (i.e., not explicitly vectorized) version only via "make scalar". 

@LaurentPlagne regarding the overhead, please notice that HPTT also exposes an expert interface via execute_expert<...> which indeed entirely avoid the overhead of spawning threads. Moreover, this interface is especially useful if HPTT is called from within a parallel region where threads have already been spawned.

**Comment by LaurentPlagne** [comment]
Oops, I am discovering HPTT and I missed the execute_expert<...> API. Thank you for mentioning it !

**Comment by springer13** [comment]
No worries, HPTT is not (well) documented. I will have to find the time to do this at some point. In the meantime, please feel free to open issues if you run into any problems.

**Comment by solomonik** [comment]
Now builds with clang for me and runs with CTF without error when building with make scalar.  My desktop evidently does not have AVX.  Will test on some larger machines eventually that ought to have AVX.

Thanks for your help!
